# Generated by Django 5.0.6 on 2024-06-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_trajet_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
