# Generated by Django 5.0.6 on 2024-06-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_trajet_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='preuve',
            field=models.ImageField(blank=True, null=True, upload_to='preuve/'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='ref',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
