# Generated by Django 5.0.6 on 2024-07-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_customuser_est_conducteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='numero',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
