# Generated by Django 5.0.6 on 2024-07-10 12:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_vehicule_nb_colonne_vehicule_nb_rangee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='siegeNumero',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
