# Generated by Django 5.0.6 on 2024-07-15 09:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_reservation_siegenumero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='attribute',
        ),
        migrations.AddField(
            model_name='trajet',
            name='siegeResever',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
