# Generated by Django 5.0.6 on 2024-07-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_trajet_attribute_trajet_siegeresever'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trajet',
            old_name='siegeResever',
            new_name='siegeReserver',
        ),
    ]
