# Generated by Django 5.0.6 on 2024-07-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_siegeresever_trajet_siegereserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='nom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='refapp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
